name: FirstPluginThree
version: '${project.version}'
main: me.roupen.firstpluginthree.FirstPluginThree
api-version: 1.19
load: STARTUP
commands:
  profile:
    description: Shows your profile
    usage: /<command>
    #permission: FirstPluginThree.profile
    permission-message: Sorry! You don't have permission to execute that command.

  weather_report:
    description: Gives a weather report of your current biome
    usage: /<command>
    #permission: FirstPluginThree.weather_report
    permission-message: Sorry! You don't have permission to execute that command.

  stats:
    description: Displays all of your current stats, considering your held equipment
    usage: /<command>
    #permission: FirstPluginThree.stats
    permission-message: Sorry! You don't have permission to execute that command.

  sethome:
    description: Sets your home location to the position you are standing
    usage: /<command>
    #permission: FirstPluginThree.stats
    permission-message: Sorry! You don't have permission to execute that command.

  home:
    description: teleports you to your set home location
    usage: /<command>
    #permission: FirstPluginThree.stats
    permission-message: Sorry! You don't have permission to execute that command.

  party:
    description: Edits your current party members
    usage: /<command>
    #permission: FirstPluginThree.stats
    permission-message: Sorry! You don't have permission to execute that command.