name: FirstPluginThree
version: '${project.version}'
main: me.roupen.firstpluginthree.FirstPluginThree
api-version: 1.19
load: STARTUP
commands:
  profile:
    description: Shows your profile
    usage: /<command>
    #permission: FirstPluginThree.profile
    permission-message: Sorry! You don't have permission to execute that command.

  weather_report:
    description: Gives a weather report of your current biome
    usage: /<command>
    #permission: FirstPluginThree.weather_report
    permission-message: Sorry! You don't have permission to execute that command.

  stats:
    description: Displays all of your current stats, considering your held equipment
    usage: /<command>
    #permission: FirstPluginThree.stats
    permission-message: Sorry! You don't have permission to execute that command.

  sethome:
    description: Sets your home location to the position you are standing
    usage: /<command>
    #permission: FirstPluginThree.sethome
    permission-message: Sorry! You don't have permission to execute that command.

  home:
    description: teleports you to your set home location
    usage: /<command>
    #permission: FirstPluginThree.home
    permission-message: Sorry! You don't have permission to execute that command.

  party:
    description: use /party help for more info
    usage: /<command>
    #permission: FirstPluginThree.party
    permission-message: Sorry! You don't have permission to execute that command.

  minimum_loot_level:
    description: Disables equipment dropping from mobs you kill below given level
    usage: /<command> <minLevel>
    #permission: FirstPluginThree.minimum_loot_level
    permission-message: Sorry! You don't have permission to execute that command.

  enemy_create:
    description: Debug command for use by admins only
    usage: /<command> <level> <mobCount>
    permission: FirstPluginThree.enemy_create
    permission-message: Sorry! You don't have permission to execute that command.

  player_reset:
    description: Debug command for use by admins only
    usage: /<command> <player>
    permission: FirstPluginThree.player_reset
    permission-message: Sorry! You don't have permission to execute that command.
